
package formularios;

import controladores.UsuarioController;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.Usuario;

public class Resultado extends javax.swing.JFrame {
    private Usuario usuario;
    private UsuarioController usuarioController = new UsuarioController();
    private static Inicio inicio;
    private DefaultTableModel modeloTablaAmbientes;
    /**
     * Creates new form Resultado
     */
    public Resultado() {
        initComponents();
        setLocationRelativeTo(null);
    }
    public Resultado(Usuario _usuario) {
        initComponents();
        setLocationRelativeTo(null);
        this.usuario=_usuario;
        //inicializar tabla
        modeloTablaAmbientes=new DefaultTableModel();
        modeloTablaAmbientes.addColumn("Ambiente");
        modeloTablaAmbientes.addColumn("Valor Promedio");
        tableAmbientes.setModel(modeloTablaAmbientes);
        darPrivilegiosSegunNivel(usuario);
        if(usuario.getNivel()==3)
        {
            String nombre = usuario.getNombre()+" "+usuario.getApellido();
            llenarTablaAmbientes(usuario.getCedula(),nombre);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        txtCedulaBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAmbientes = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        lblNombreEstudiante = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setText("RSULTADOS");

        lblCedula.setText("Cédula:");

        tableAmbientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Ambiente", "Valor Promedio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableAmbientes.setEnabled(false);
        tableAmbientes.setFocusable(false);
        tableAmbientes.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(tableAmbientes);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(lblCedula)
                        .addGap(18, 18, 18)
                        .addComponent(txtCedulaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(btnRegresar)))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreEstudiante)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedula)
                    .addComponent(txtCedulaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNombreEstudiante)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegresar)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String cedula=txtCedulaBuscar.getText();
        Usuario estudiante = new Usuario();
        //validar que la cedula contega solo numeros 
        if(!validarSoloNumeros(cedula.trim())||txtCedulaBuscar.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Ingrese un número cédula válido: Debe estar compuesta por 10 dígitos numéricos");
            return;
        }
        //Traer datos del estudiante 
        estudiante=usuarioController.UsuarioPorCedula(cedula);
        String nombre = estudiante.getNombre()+" "+estudiante.getApellido();
        llenarTablaAmbientes(cedula,nombre);
    }//GEN-LAST:event_btnBuscarActionPerformed
private boolean validarSoloNumeros(String cadena)
{
    Pattern pattern = Pattern.compile("[0-9]{10}");
    Matcher matcher=pattern.matcher(cadena);
    return matcher.find();
}
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();
        inicio=new Inicio(usuario);
        inicio.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resultado().setVisible(true);
            }
        });
    }
private void llenarTablaAmbientes(String cedula,String nombre)
{
    limpiarTabla();
    lblNombreEstudiante.setText(nombre);
    ArrayList<Object[]> resultadoConsulta = usuarioController.ResultadoPorCedula(cedula);
    for(int i=0;i<6;i++)
    {
        modeloTablaAmbientes.addRow(resultadoConsulta.get(i));
    }
}
private void darPrivilegiosSegunNivel(Usuario usuario)
{
    if(usuario.getNivel() ==3)
    {
        txtCedulaBuscar.setVisible(false);
        btnBuscar.setVisible(false);
        lblCedula.setVisible(false);
    }
}
private void limpiarTabla()
{
    modeloTablaAmbientes.getDataVector().removeAllElements();
    tableAmbientes.updateUI();
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblNombreEstudiante;
    private javax.swing.JTable tableAmbientes;
    private javax.swing.JTextField txtCedulaBuscar;
    // End of variables declaration//GEN-END:variables
}
